# Generated by Django 3.1.7 on 2021-03-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follower_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follower_following',
        ),
    ]
