# Generated by Django 3.1.7 on 2021-04-11 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follower_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('on_which_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_this_post', to='network.post')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_liked_this_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
