# Generated by Django 3.1.7 on 2021-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=models.ImageField(default='Default_background.jpg', upload_to='bg_img'),
        ),
    ]
